=== DionKoolhaas/open-api-specs/duo/rio/aangeboden-vavo-opleiding-cohort.json
{
	"__comment__": "Gegenereerd op basis van commit#164 in het DUO_RIO_Linked_Data op 20190904 om 11:54. Gemaakt met template-jsonschema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "AangebodenVavoOpleidingCohort JSON-Schema",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"_links": {
			"properties": {
				"self": {
					"description": "Absolute link naar deze resource",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"aangebodenVavoOpleiding": {
					"description": "AangebodenVavoOpleiding heeft een associatie (http://lod.onderwijsregistratie.nl/cat/rio/def/heeftAanmeldingscohort) met deze resource AangebodenVavoOpleidingCohort",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
			},
			"required": [
				"self"
				,"aangebodenVavoOpleiding"
			],
			"type": "object"
		},
		"uri": {
			"type": "string",
			"format": "uri",
			"description": "URI van de specifieke resource"
		},
		"code": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/aangebodenOpleidingscohortidentifcatie-v01",
				"description": "aangebodenOpleidingscohortidentifcatie-v01"
			},
			"description": "Is een door de onderwijsaanbieder bepaald identificerend kenmerk van een aangeboden opleidingcohort ten behoeve van uitwisseling in de keten.",
			"maxLength": 60,
			"minLength": 1
		},
		"status": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/cohortstatus-v01",
				"description": "cohortstatus-v01"
			},
			"description": "De toegestane waarden voor de status van een cohort van een aangeboden opleiding.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"beginAanmeldperiode": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/aanmeldingscohortbegindatum-v01",
				"description": "aanmeldingscohortbegindatum-v01"
			},
			"description": "Is de eerste dag waarop een aspirant-student zich aan kan melden voor het betreffende cohort van een aangeboden opleiding. ",
			"format": "date"
		},
		"eindeAanmeldperiode": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/aanmeldingscohorteinddatum-v01",
				"description": "aanmeldingscohorteinddatum-v01"
			},
			"description": "Is de laatste dag waarop een aspirant-student zich aan kan melden voor het betreffende cohort van een aangeboden opleiding. ",
			"format": "date"
		},
		"instroommoment": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/cohortaanvangsdatum-v01",
				"description": "cohortaanvangsdatum-v01"
			},
			"description": "De dag waarop het cohort voor de aangeboden opleiding begint. ",
			"format": "date"
		},
		"beginInstroomperiode": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/instroomperiodeCohortbegindatum-v01",
				"description": "instroomperiodeCohortbegindatum-v01"
			},
			"description": "De eerste dag dat een student in een cohort van een aangeboden opleiding met een flexibele instroom kan beginnen. ",
			"format": "date"
		},
		"eindeInstroomperiode": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/instroomperiodeCohorteinddatum-v01",
				"description": "instroomperiodeCohorteinddatum-v01"
			},
			"description": "De laatste dag dat een student kan beginnen in een cohort van een aangeboden opleiding met een flexibele instroom. ",
			"format": "date"
		},
		"toestemmingVereistVoorAanmelding": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/toestemmingAanmeldingscohortVereist-v01",
				"description": "toestemmingAanmeldingscohortVereist-v01"
			},
			"description": "Geeft aan of een aspirant student voor een bepaald cohort van een aangeboden opleidng toestemming van de instelling nodig heeft om zich aan te mogen melden.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"toelichtingVereisteToestemming": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/toestemmingAanmeldingscohorttoelichting-v01",
				"description": "toestemmingAanmeldingscohorttoelichting-v01"
			},
			"description": "Is een tekstuele toelichting op de voor aanmelding vereiste toestemming van de onderwijsaanbieder.",
			"maxLength": 3000,
			"minLength": 1
		}
	},
	"required": [
		"_links",
		"code",
		"status",
		"beginAanmeldperiode",
		"toestemmingVereistVoorAanmelding"
	]
}

=== DionKoolhaas/open-api-specs/duo/rio/examples/aangeboden-vavo-opleiding-cohort.json
{
  "_links": {
	"self": {
		"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/aangeboden-vavo-opleiding-cohorten/0180-COHORT-2"
	},
	"aangebodenVavoOpleiding": {
		"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/aangeboden-vavo-opleidingen?aangebodenVavoOpleidingCohorthttp://lod.onderwijsregistratie.nl/cat/rio/id/AangebodenVavoOpleidingCohort/0180-COHORT-2"
		}
	},
	"uri": "http://lod.onderwijsregistratie.nl/cat/rio/id/AangebodenVavoOpleidingCohort/0180-COHORT-2",
    "code": "0180-COHORT-2",
    "status": "O",
    "beginAanmeldperiode": "2018-04-23",
    "eindeAanmeldperiode": "2019-07-31",
    "instroommoment": "2018-08-01",
    "toestemmingVereistVoorAanmelding": "NEE"
}
