=== DionKoolhaas/open-api-specs/duo/rio/mbo-onderwijslicentie.json
{
	"__comment__": "Gegenereerd op basis van commit#158 in het DUO_RIO_Linked_Data op 20190801 om 13:19. Gemaakt met template-jsonschema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "MboOnderwijslicentie JSON-Schema",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"_links": {
			"properties": {
				"self": {
					"description": "Absolute link naar deze resource",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"onderwijsinstellingserkenning": {
					"description": "Deze resource heeft een associatie geeftToestemmingAan met Onderwijsinstellingserkenning",
					"externalDocs": { 
						"url": "http://lod.onderwijsregistratie.nl/cat/rio/def/geeftToestemmingAan",
						"description": "geeftToestemmingAan"
					},
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"mboOpleidingserkenning": {
					"description": "Deze resource heeft een associatie geeftToestemmingVoor met MboOpleidingserkenning",
					"externalDocs": { 
						"url": "http://lod.onderwijsregistratie.nl/cat/rio/def/geeftToestemmingVoor",
						"description": "geeftToestemmingVoor"
					},
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
			},
			"required": [
				"self"
				,"onderwijsinstellingserkenning"
				,"mboOpleidingserkenning"
			],
			"type": "object"
		},
		"uri": {
			"type": "string",
			"format": "uri",
			"description": "URI van de specifieke resource"
		},
		"leerweg": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/leerwegMBO-v04",
				"description": "leerwegMBO-v04"
			},
			"description": "Uitputtende lijst ten behoeve van de onderwijssector MBO (Middelbaar Beroepsonderwijs) voor de manier waarop de kennisoverdracht is ingericht wat betreft fysieke aanwezigheid op de onderwijslocatie en de duur daarvan.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"stadium": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/licentiestadium-v01",
				"description": "licentiestadium-v01"
			},
			"description": "De toestand waarin een licentie zich bevindt.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"bekostigd": {
			"type": "boolean",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/bekostigingsIndicatie",
				"description": "bekostigingsIndicatie"
			},
			"description": "De bekostigingsindicatie geeft aan of een inschrijving, graad, licentie of instelling in aanmerking komt voor bekostiging in de vorm van een rijksbijdrage."
		},
		"begindatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeBegindatum-v01",
				"description": "periodeBegindatum-v01"
			},
			"description": "De datum die het begin van de periode aangeeft (inclusief).",
			"format": "date"
		},
		"einddatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeEinddatum-v01",
				"description": "periodeEinddatum-v01"
			},
			"description": "De datum die het einde van de periode aangeeft (exclusief).",
			"format": "date"
		}
	},
	"required": [
		"_links",
		"leerweg",
		"stadium",
		"bekostigd",
		"begindatum"
	]
}

=== DionKoolhaas/open-api-specs/duo/rio/examples/mbo-onderwijslicentie.json
{
  "_links": {
    "self": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/mbo-onderwijslicenties/24CE10505"
    },
	"onderwijsinstellingserkenning": {
		"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/onderwijsinstellingserkenningen?mboOnderwijslicentie=http://lod.onderwijsregistratie.nl/rio/id/MboOnderwijslicentie/24CE10505"
    },
	"mboOpleidingserkenning": {
      	"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/mbo-opleidingserkenningen?mboOnderwijslicentie=http://lod.onderwijsregistratie.nl/rio/id/MboOnderwijslicentie/24CE10505"
    }
  },
  "uri": "http://lod.onderwijsregistratie.nl/rio/id/MboOnderwijslicentie/24CE10505",
  "begindatum": "1997-08-01",
  "einddatum": "2017-08-01",
  "stadium": "STANDAARD",
  "bekostigd": true,
  "leerweg": "BOL"
}
