=== DionKoolhaas/open-api-specs/duo/rio/vavo-opleidingserkenning.json
{
	"__comment__": "Gegenereerd op basis van commit#164 in het DUO_RIO_Linked_Data op 20190904 om 11:54. Gemaakt met template-jsonschema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "VavoOpleidingserkenning JSON-Schema",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"_links": {
			"properties": {
				"self": {
					"description": "Absolute link naar deze resource",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"vavoOnderwijslicentie": {
					"description": "VavoOnderwijslicentie heeft een associatie (http://lod.onderwijsregistratie.nl/cat/rio/def/geeftToestemmingVoor) met deze resource VavoOpleidingserkenning",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"voOpleiding": {
					"description": "VoOpleiding heeft een associatie (http://lod.onderwijsregistratie.nl/cat/rio/def/wordtErkendAls) met deze resource VavoOpleidingserkenning",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
			},
			"required": [
				"self"
				,"vavoOnderwijslicentie"
				,"voOpleiding"
			],
			"type": "object"
		},
		"uri": {
			"type": "string",
			"format": "uri",
			"description": "URI van de specifieke resource"
		},
		"ingangsdatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeBegindatum-v01",
				"description": "periodeBegindatum-v01"
			},
			"description": "De datum die het begin van de periode aangeeft (inclusief).",
			"format": "date"
		},
		"einddatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeEinddatum-v01",
				"description": "periodeEinddatum-v01"
			},
			"description": "De datum die het einde van de periode aangeeft (exclusief).",
			"format": "date"
		},
		"ministerie": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/ministerieAanduiding-v02",
				"description": "ministerieAanduiding-v02"
			},
			"description": "Het ministerie waaronder een opleiding of instelling ressorteert.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"opleidingsstelsel": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/opleidingsstelsel-v07",
				"description": "opleidingsstelsel-v07"
			},
			"description": "De naam van het codestelsel waarbinnen samenhangende erkende opleidingen of vakken uniek onderscheiden worden.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"opleidingcode": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/opleidingcode",
				"description": "opleidingcode"
			},
			"description": "De code van de opleiding binnen het codestelsel",
			"maxLength": 8,
			"minLength": 1
		},
		"wet": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/wet-v02",
				"description": "wet-v02"
			},
			"description": "Wet waarin of waaronder de juridische grondslag bepaald is.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		}
	},
	"required": [
		"_links",
		"ingangsdatum",
		"ministerie",
		"opleidingsstelsel",
		"opleidingcode",
		"wet"
	]
}

=== DionKoolhaas/open-api-specs/duo/rio/examples/vavo-opleidingserkenning.json
{
  "_links": {
    "self": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/vavo-opleidingserkenningen/5250"
    },
    "voOpleiding": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/vo-opleidingen?vavoOpleidingserkenning=http://lod.onderwijsregistratie.nl/rio/id/MboOpleidingserkenning/97552"
    },
    "vavoOnderwijslicentie": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/vavo-onderwijslicenties?vavoOpleidingserkenning=http://lod.onderwijsregistratie.nl/rio/id/MboOpleidingserkenning/97552"
    }
  },
  "uri": "http://lod.onderwijsregistratie.nl/rio/id/VavoOpleidingserkenning/5250",
  "ingangsdatum": "2008-08-01",
  "einddatum": "2013-08-01",
  "wet": "WEB",
  "ministerie" : "EZ",
  "opleidingsstelsel": "KSE",
  "opleidingcode": "5250"
}
