=== DionKoolhaas/open-api-specs/duo/rio/jsonschemas/examenlicentie.json
{
	"__comment__": "Gegenereerd op basis van commit#164 in het DUO_RIO_Linked_Data op 20190904 om 11:54. Gemaakt met template-jsonschema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Examenlicentie JSON-Schema",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"_links": {
			"properties": {
				"self": {
					"description": "Absolute link naar deze resource",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"onderwijsinstellingserkenning": {
					"description": "Deze resource heeft een associatie geeftToestemmingAan met Onderwijsinstellingserkenning",
					"externalDocs": { 
						"url": "http://lod.onderwijsregistratie.nl/cat/rio/def/geeftToestemmingAan",
						"description": "geeftToestemmingAan"
					},
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"mboOpleidingserkenning": {
					"description": "Deze resource heeft een associatie geeftToestemmingVoor met MboOpleidingserkenning",
					"externalDocs": { 
						"url": "http://lod.onderwijsregistratie.nl/cat/rio/def/geeftToestemmingVoor",
						"description": "geeftToestemmingVoor"
					},
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
			},
			"required": [
				"self"
				,"onderwijsinstellingserkenning"
				,"mboOpleidingserkenning"
			],
			"type": "object"
		},
		"uri": {
			"type": "string",
			"format": "uri",
			"description": "URI van de specifieke resource"
		},
		"stadium": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/licentiestadium-v01",
				"description": "licentiestadium-v01"
			},
			"description": "De toestand waarin een licentie zich bevindt.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"begindatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeBegindatum-v01",
				"description": "periodeBegindatum-v01"
			},
			"description": "De datum die het begin van de periode aangeeft (inclusief).",
			"format": "date"
		},
		"einddatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeEinddatum-v01",
				"description": "periodeEinddatum-v01"
			},
			"description": "De datum die het einde van de periode aangeeft (exclusief).",
			"format": "date"
		}
	},
	"required": [
		"_links",
		"stadium",
		"begindatum"
	]
}

=== DionKoolhaas/open-api-specs/duo/rio/examples/examenlicentie.json
{
  "_links": {
    "self": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/examenlicenties/25LT90622"
    },
	"onderwijsinstellingserkenning": {
		"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/onderwijsinstellingserkenningen?examenlicentie=http://lod.onderwijsregistratie.nl/rio/id/Examenlicentie/25LT90622"
    },
	"mboOpleidingserkenning": {
      	"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/mbo-opleidingserkenningen?examenlicentie=http://lod.onderwijsregistratie.nl/rio/id/Examenlicentie/25LT90622"
    }
  },
  "uri": "http://lod.onderwijsregistratie.nl/rio/id/Examenlicentie/25LT90622",
  "begindatum": "2007-08-01",
  "einddatum": "2017-08-01",
  "stadium": "STANDAARD"
}
