=== DionKoolhaas/open-api-specs/duo/rio/jsonschemas/mbo-domein.json
{
	"__comment__": "Gegenereerd op basis van commit#164 in het DUO_RIO_Linked_Data op 20190904 om 11:54. Gemaakt met template-jsonschema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "MboDomein JSON-Schema",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"_links": {
			"properties": {
				"self": {
					"description": "Absolute link naar deze resource",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"mboOpleidingserkenning": {
					"description": "Deze resource heeft een associatie wordtErkendAls met MboOpleidingserkenning",
					"externalDocs": { 
						"url": "http://lod.onderwijsregistratie.nl/cat/rio/def/wordtErkendAls",
						"description": "wordtErkendAls"
					},
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"aangebodenMboOpleiding": {
					"description": "AangebodenMboOpleiding heeft een associatie (http://lod.onderwijsregistratie.nl/cat/rio/def/isVanHetSoort) met deze resource MboDomein",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"mboKwalificatiedossier": {
					"description": "MboKwalificatiedossier heeft een associatie (http://lod.onderwijsregistratie.nl/cat/rio/def/maaktDeelUitVan) met deze resource MboDomein",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
			},
			"required": [
				"self"
				,"mboOpleidingserkenning"
				,"aangebodenMboOpleiding"
				,"mboKwalificatiedossier"
			],
			"type": "object"
		},
		"uri": {
			"type": "string",
			"format": "uri",
			"description": "URI van de specifieke resource"
		},
		"code": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/opleidingcode",
				"description": "opleidingcode"
			},
			"description": "De code van de opleiding binnen het codestelsel",
			"maxLength": 8,
			"minLength": 1
		},
		"naam": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/naamOpleidingKort",
				"description": "naamOpleidingKort"
			},
			"description": "Korte naam voor een opleiding",
			"maxLength": 40,
			"minLength": 1
		},
		"naamLang": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/naamOpleidingLang",
				"description": "naamOpleidingLang"
			},
			"description": "Lange naam voor een opleiding",
			"maxLength": 225,
			"minLength": 1
		},
		"internationaleNaam": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/internationaleNaamOpleiding-v02",
				"description": "internationaleNaamOpleiding-v02"
			},
			"description": "De naam voor internationaal gebruik ter aanduiding van de  opleiding.",
			"maxLength": 225,
			"minLength": 1
		},
		"afkorting": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/aanduidingOpleiding-v01",
				"description": "aanduidingOpleiding-v01"
			},
			"description": "Is een korte omschrijving van de naam van de opleiding.",
			"maxLength": 12,
			"minLength": 1
		},
		"herkomstOpleiding": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/opleidingsherkomst-v01",
				"description": "opleidingsherkomst-v01"
			},
			"description": "Geeft aan welke instantie de Opleiding heeft ontwikkeld.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"structuur": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/mBOStructuursoorttype-v01",
				"description": "mBOStructuursoorttype-v01"
			},
			"description": "Unieke codering voor de stelsels binnen de MBO structuur.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"startdatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeBegindatum-v01",
				"description": "periodeBegindatum-v01"
			},
			"description": "De datum die het begin van de periode aangeeft (inclusief).",
			"format": "date"
		},
		"opheffingsdatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeEinddatum-v01",
				"description": "periodeEinddatum-v01"
			},
			"description": "De datum die het einde van de periode aangeeft (exclusief).",
			"format": "date"
		},
		"_embedded": {
			"type": "object",
			"properties": {
				"mboOpleidingserkenning": {
					"type": "array",
					"items": {
						"$ref": "mbo-opleidingserkenning.json"
					}
				}
			}
		}
	},
	"required": [
		"_links",
		"code",
		"naamLang",
		"herkomstOpleiding",
		"startdatum"
	]
}

=== DionKoolhaas/open-api-specs/duo/rio/examples/mbo-domein.json
{
  "_links": {
    "self": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/examenlicenties/25LT90622"
    },
	"mboOpleidingserkenning": {
      	"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/mbo-opleidingserkenningen?mboDomein=http://lod.onderwijsregistratie.nl/cat/rio/id/MboDomein/92090"
    },
	"aangebodenMboOpleiding": {
		"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/aangeboden-mbo-opleidingen?mboDomein=http://lod.onderwijsregistratie.nl/cat/rio/id/MboDomein/92090"
	},
    "aangebodenMboOpleiding": {
		"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/aangeboden-mbo-opleidingen?mboDomein=http://lod.onderwijsregistratie.nl/cat/rio/id/MboDomein/92090"
	},
    "mboKwalificatiedossier": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/mbo-kwalificaties-dossiers?mboDomein=http://lod.onderwijsregistratie.nl/cat/rio/id/MboDomein/92090"
    }
  },
  "uri": "http://lod.onderwijsregistratie.nl/cat/rio/id/MboDomein/92090",
  "code": "92090",
  "naam": "Bouw en infra",
  "naamLang": "Bouw en infra",
  "afkorting": "B & I",
  "herkomstOpleiding": "SBB",
  "startdatum": "2017-08-01"
}
