=== DionKoolhaas/open-api-specs/duo/rio/jsonschemas/mbo-kwalificatie.json
{
	"__comment__": "Gegenereerd op basis van commit#164 in het DUO_RIO_Linked_Data op 20190904 om 11:54. Gemaakt met template-jsonschema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "MboKwalificatie JSON-Schema",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"_links": {
			"properties": {
				"self": {
					"description": "Absolute link naar deze resource",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"mboKwalificatiedossier": {
					"description": "Deze resource heeft een associatie maaktDeelUitVan met MboKwalificatiedossier",
					"externalDocs": { 
						"url": "http://lod.onderwijsregistratie.nl/cat/rio/def/maaktDeelUitVan",
						"description": "maaktDeelUitVan"
					},
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"mboOpleidingserkenning": {
					"description": "Deze resource heeft een associatie wordtErkendAls met MboOpleidingserkenning",
					"externalDocs": { 
						"url": "http://lod.onderwijsregistratie.nl/cat/rio/def/wordtErkendAls",
						"description": "wordtErkendAls"
					},
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"aangebodenMboOpleiding": {
					"description": "AangebodenMboOpleiding heeft een associatie (http://lod.onderwijsregistratie.nl/cat/rio/def/isVanHetSoort) met deze resource MboKwalificatie",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
			},
			"required": [
				"self"
				,"mboKwalificatiedossier"
				,"mboOpleidingserkenning"
				,"aangebodenMboOpleiding"
			],
			"type": "object"
		},
		"uri": {
			"type": "string",
			"format": "uri",
			"description": "URI van de specifieke resource"
		},
		"code": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/opleidingcode",
				"description": "opleidingcode"
			},
			"description": "De code van de opleiding binnen het codestelsel",
			"maxLength": 8,
			"minLength": 1
		},
		"naam": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/naamOpleidingKort",
				"description": "naamOpleidingKort"
			},
			"description": "Korte naam voor een opleiding",
			"maxLength": 40,
			"minLength": 1
		},
		"naamLang": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/naamOpleidingLang",
				"description": "naamOpleidingLang"
			},
			"description": "Lange naam voor een opleiding",
			"maxLength": 225,
			"minLength": 1
		},
		"internationaleNaam": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/internationaleNaamOpleiding-v02",
				"description": "internationaleNaamOpleiding-v02"
			},
			"description": "De naam voor internationaal gebruik ter aanduiding van de  opleiding.",
			"maxLength": 225,
			"minLength": 1
		},
		"afkorting": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/aanduidingOpleiding-v01",
				"description": "aanduidingOpleiding-v01"
			},
			"description": "Is een korte omschrijving van de naam van de opleiding.",
			"maxLength": 12,
			"minLength": 1
		},
		"herkomstOpleiding": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/opleidingsherkomst-v01",
				"description": "opleidingsherkomst-v01"
			},
			"description": "Geeft aan welke instantie de Opleiding heeft ontwikkeld.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"opleidingssoort": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/beroepsopleidingsoort-v01",
				"description": "beroepsopleidingsoort-v01"
			},
			"description": "Opsomming van de mogelijke soorten beroepsopleidingen zoals die in de Wet Educatie en Beroepsonderwijs worden onderkend.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"wetEisendMinisterie": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/wetEisendMinisterie-v03",
				"description": "wetEisendMinisterie-v03"
			},
			"description": "Het ministerie dat wettelijke eisen stelt aan de opleiding.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"niveau": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/kwalificatieniveau-v03",
				"description": "kwalificatieniveau-v03"
			},
			"description": "De aanduiding van het niveau van beroepsuitoefening, gebaseerd op de mate van verantwoordelijkheid en complexiteit.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9\\-]*$"
		},
		"studielasteenheid": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/studielastEenheid-v03",
				"description": "studielastEenheid-v03"
			},
			"description": "De meeteenheid voor de studielast",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"studielast": {
			"type": "integer",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/studielastZwaarte",
				"description": "studielastZwaarte"
			},
			"description": "Een getal dat de inspanning weergeeft die de opleiding vergt.",
			"pattern": "^\\d{0,5}$"
		},
		"waardedocumentsoort": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/soortWaardedocument-v01",
				"description": "soortWaardedocument-v01"
			},
			"description": "Aanduiding van het soort waardedocument dat kan worden of is behaald.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"structuur": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/mBOStructuursoorttype-v01",
				"description": "mBOStructuursoorttype-v01"
			},
			"description": "Unieke codering voor de stelsels binnen de MBO structuur.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"startdatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeBegindatum-v01",
				"description": "periodeBegindatum-v01"
			},
			"description": "De datum die het begin van de periode aangeeft (inclusief).",
			"format": "date"
		},
		"opheffingsdatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeEinddatum-v01",
				"description": "periodeEinddatum-v01"
			},
			"description": "De datum die het einde van de periode aangeeft (exclusief).",
			"format": "date"
		}
	},
	"required": [
		"_links",
		"code",
		"naamLang",
		"herkomstOpleiding",
		"opleidingssoort",
		"wetEisendMinisterie",
		"niveau",
		"studielasteenheid",
		"studielast",
		"waardedocumentsoort",
		"startdatum"
	]
}

=== DionKoolhaas/open-api-specs/duo/rio/examples/mbo-kwalificatie.json
{
  "_links": {
    "self": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/examenlicenties/25LT90622"
    },
	"mboOpleidingserkenning": {
      	"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/mbo-opleidingserkenningen?mboKwalificatie=http://lod.onderwijsregistratie.nl/cat/rio/id/MboKwalificatie/25172"
    },
	"aangebodenMboOpleiding": {
		"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/aangeboden-mbo-opleidingen?mboKwalificatie=http://lod.onderwijsregistratie.nl/cat/rio/id/MboKwalificatie/25172"
	},
    "mboKwalificatiedossier": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/mbo-kwalificaties-dossiers?mboKwalificatie=http://lod.onderwijsregistratie.nl/cat/rio/id/MboKwalificatie/25172"
    }
  },
  "uri": "http://lod.onderwijsregistratie.nl/cat/rio/id/MboKwalificatie/25172",
  "code": "25172",
  "naam": "Leidinggevende bakkerij",
  "naamLang": "Leidinggevende bakkerij",
  "afkorting": "B & I",
  "herkomstOpleiding": "SBB",
  "startdatum": "2015-08-01",
  "opleidingssoort": "MIDDENKADEROPLEIDING",
  "wetEisendMinisterie": "DEF",
  "studielasteenheid": "SBU",
  "studielast": 6400,
  "niveau": "MBO-4",
  "waardedocumentsoort": "DIPLOMA"
}
