=== DionKoolhaas/open-api-specs/duo/rio/jsonschemas/nederlands-adres.json
{
	"__comment__": "Gegenereerd op basis van commit#164 in het DUO_RIO_Linked_Data op 20190904 om 11:54. Gemaakt met template-jsonschema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "NederlandsAdres JSON-Schema",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"_links": {
			"properties": {
				"self": {
					"description": "Absolute link naar deze resource",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"communicatiecontext": {
					"description": "Communicatiecontext heeft een associatie (http://lod.onderwijsregistratie.nl/cat/rio/def/isViaPostBereikbaarOp) met deze resource NederlandsAdres",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"communicatiecontext": {
					"description": "Communicatiecontext heeft een associatie (http://lod.onderwijsregistratie.nl/cat/rio/def/isTeBezoekenOp) met deze resource NederlandsAdres",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
			},
			"required": [
				"self"
				,"communicatiecontext"
				,"communicatiecontext"
			],
			"type": "object"
		},
		"uri": {
			"type": "string",
			"format": "uri",
			"description": "URI van de specifieke resource"
		},
		"straatnaam": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/straatnaam-v02",
				"description": "straatnaam-v02"
			},
			"description": "De straatnaam zoals die officieel is vastgesteld door de gemeente",
			"maxLength": 80,
			"minLength": 1
		},
		"huisnummer": {
			"type": "integer",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/huisnummer-v03",
				"description": "huisnummer-v03"
			},
			"description": "De numerieke aanduiding zoals deze door het gemeentebestuur aan het object is toegekend"
		},
		"huisnummertoevoeging": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/huisnummertoevoegingNEN-v02",
				"description": "huisnummertoevoegingNEN-v02"
			},
			"description": "Die letters of tekens die noodzakelijk zijn om, naast het juiste huisnummer, de brievenbus te vinden",
			"maxLength": 6,
			"minLength": 1
		},
		"postcode": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/postcode-v02",
				"description": "postcode-v02"
			},
			"description": "De door de Post NL vastgestelde code behorend bij de straatnaam en het huisnummer dan wel de door Post NL vastgestelde code behorende bij een bepaalde combinatie van een naam openbare ruimte en een huisnummer.",
			"maxLength": 6,
			"pattern": "^([1-9]{1}[0-9]{3}[A-Z]{2})$"
		},
		"plaatsnaam": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/plaatsnaam-v02",
				"description": "plaatsnaam-v02"
			},
			"description": "De naam van de plaats ",
			"maxLength": 40,
			"minLength": 1
		}
	},
	"required": [
		"_links",
		"straatnaam",
		"huisnummer",
		"postcode",
		"plaatsnaam"
	]
}

=== DionKoolhaas/open-api-specs/duo/rio/examples/nederlands-adres.json
{
  "_links": {
    "self": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/nederlands-adressen/7311PE27"
    },
	"communicatiecontext": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/communicatiecontexten?nederlandsadres=http://lod.onderwijsregistratie.nl/rio/id/NederlandsAdres/7311PE27"
    }
  },
  "uri": "http://lod.onderwijsregistratie.nl/rio/id/NederlandsAdres/7311PE27",
  "straatnaam": "Spoorstraat",
  "huisnummer": 27,
  "huisnummertoevoeging": "97552",
  "postcode": "7311PE",
  "plaatsnaam": "APELDOORN"
}
