=== DionKoolhaas/open-api-specs/duo/rio/jsonschemas/vo-groep.json
{
	"__comment__": "Gegenereerd op basis van commit#164 in het DUO_RIO_Linked_Data op 20190904 om 11:54. Gemaakt met template-jsonschema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "VoGroep JSON-Schema",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"_links": {
			"properties": {
				"self": {
					"description": "Absolute link naar deze resource",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"aangebodenVavoOpleiding": {
					"description": "AangebodenVavoOpleiding heeft een associatie (http://lod.onderwijsregistratie.nl/cat/rio/def/isVanHetSoort) met deze resource VoGroep",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
				,
				"voOpleiding": {
					"description": "VoOpleiding heeft een associatie (http://lod.onderwijsregistratie.nl/cat/rio/def/maaktDeelUitVan) met deze resource VoGroep",
					"properties": {
						"href": {
							"description": "URL van de link",
							"format": "uri",
							"type": "string"
						}
					},
					"required": [
						"href"
					],
					"type": "object"
				}
			},
			"required": [
				"self"
				,"aangebodenVavoOpleiding"
				,"voOpleiding"
			],
			"type": "object"
		},
		"uri": {
			"type": "string",
			"format": "uri",
			"description": "URI van de specifieke resource"
		},
		"code": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/opleidingcode",
				"description": "opleidingcode"
			},
			"description": "De code van de opleiding binnen het codestelsel",
			"maxLength": 8,
			"minLength": 1
		},
		"herkomstOpleiding": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/opleidingsherkomst-v01",
				"description": "opleidingsherkomst-v01"
			},
			"description": "Geeft aan welke instantie de Opleiding heeft ontwikkeld.",
			"maxLength": 70,
			"minLength": 1,
			"pattern": "^[A-Z0-9_]*$"
		},
		"naamLang": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/naamOpleidingLang",
				"description": "naamOpleidingLang"
			},
			"description": "Lange naam voor een opleiding",
			"maxLength": 225,
			"minLength": 1
		},
		"naam": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/naamOpleidingKort",
				"description": "naamOpleidingKort"
			},
			"description": "Korte naam voor een opleiding",
			"maxLength": 40,
			"minLength": 1
		},
		"internationaleNaam": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/internationaleNaamOpleiding-v02",
				"description": "internationaleNaamOpleiding-v02"
			},
			"description": "De naam voor internationaal gebruik ter aanduiding van de  opleiding.",
			"maxLength": 225,
			"minLength": 1
		},
		"afkorting": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/aanduidingOpleiding-v01",
				"description": "aanduidingOpleiding-v01"
			},
			"description": "Is een korte omschrijving van de naam van de opleiding.",
			"maxLength": 12,
			"minLength": 1
		},
		"startdatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeBegindatum-v01",
				"description": "periodeBegindatum-v01"
			},
			"description": "De datum die het begin van de periode aangeeft (inclusief).",
			"format": "date"
		},
		"opheffingsdatum": {
			"type": "string",
			"externalDocs": { 
				"url": "http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeEinddatum-v01",
				"description": "periodeEinddatum-v01"
			},
			"description": "De datum die het einde van de periode aangeeft (exclusief).",
			"format": "date"
		}
	},
	"required": [
		"_links",
		"code",
		"herkomstOpleiding",
		"naamLang",
		"startdatum"
	]
}

=== DionKoolhaas/open-api-specs/duo/rio/examples/vo-groep.json
{
  "_links": {
    "self": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/vo-groepen/1000"
    },
	"aangebodenVavoOpleiding": {
		"href": "https://lod.onderwijsregistratie.nl/api/rio/v1/aangeboden-vavo-opleidingen?voGroep=http://lod.onderwijsregistratie.nl/rio/id/VoGroep/1000"
	},
    "voOpleiding": {
      "href": "https://lod.onderwijsregistratie.nl/api/rio/v1/vo-opleidingen?voGroep=http://lod.onderwijsregistratie.nl/rio/id/VoGroep/1000"
    }
  },
  "uri": "http://lod.onderwijsregistratie.nl/rio/id/VoGroep/1000",
  "code": "1000",
  "naam": "VMBO BB ENT BW",
  "naamLang": "VMBO BB ENT Bouwen, wonen en interieur",
  "afkorting": "VMBO ENT BW",
  "herkomstOpleiding": "OCW",
  "startdatum": "2015-08-01"
}
